"""Create a program that will play the “cows and bulls”
game with the user.
 The game works like this:

Randomly generate a 4-digit number.
Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place,
 they have a “cow”.
 For every digit the user guessed correctly in the wrong place is a “bull.”
  Every time the user makes a guess,
  tell them how many “cows” and “bulls” they have.
  Once the user guesses the correct number, the game is over.
  Keep track of the number of guesses the user makes
  throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038.
 An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...

Until the user guesses the number."""
from colorama import init,Fore,Back,Style
from  os import system
from time import sleep
import random
###______________________imported_______________
init(autoreset=True)
history=list()
def cls():
    sleep(2.5)
    system("clear")
def ran_num():
    d=str(random.randint(1000,9999))
    return d
def check_it(generated,user_given):
    global cows,bulls
    cows=0
    bulls=0
    for i in range(0,4):
        if user_given[i] == generated[i]:
            bulls+=1
        elif user_given[i] in generated:
            cows+=1
if __name__=="__main__":
  data=ran_num()  
  print(Fore.GREEN+"---------------------------Welcome to cows and bulls game ------------------------------------------ ")
  print(Fore.WHITE+""" Rules are:
             For every digit that  you guessed correctly in the correct place,
              they have a “bulls”.
              Fors every digit that you guessed correctly in the wrong place is a “cows. """)
  while True:
      
      print("Enter a 4 digit number Duplicates number not allowed")
      user=input("to get last number 'history'and to exit :[>>]")
      if user =="exit":
          print(Fore.RED+"Thanks for playing this game".center(100,"@"))
          exit()
      elif user =="history":
          print("showing history for 5 sec".center(100,"#"))
          if  len(history) ==0:
              print("history is empty")
              continue
          else:
              print(history)
          sleep(3)
          cls()
          continue
      if len(user)>4 or len(user)<4:
          print(Fore.BLUE+"error::number should only of 4 digit")
          continue
          sleep(2)
      history.append(user)
      check_it(data ,user) ## where data is  is generated and user is taken from user
      cls()
      print(Back.YELLOW+"YOU just got {} cows and {} bulls".format(cows,bulls))
      if bulls==4:
          print(Fore.WHITE+"You just won the match".center(100,"*"))
          break
      else:
          print(Fore.BLUE+"Try again ::))))".center(100,"*"))
          continue
##done
#link>>https://www.practicepython.org/exercise/2014/07/05/18-cows-and-bulls.html
